### ISSUE TITLE
Wrong bed size configuration for U30pro

### ISSUE THREAD

**Issue by poisonedPawn** [LONGER3D/Marlin1.1.9_LGT0.3.x_Alfawise_Ux0Pro#3]
### Description
The bed size configuration of the Alfawise U30pro is set to 220 for X and Y (lines 919, 920) but the printer have 235x235 bed.

**Comment by LONGER3D** [comment]
Hi, the actual size of the hot bed is 235x235. For safety, a margin of 15 mm is reserved in the setup. So, the bed size configuration of the Alfawise U30pro is set to 220 for X and Y.
